import type { DatabaseSync } from "node:sqlite";
import { withChatContentDocument, type ArtifactRecord, type ProjectRecord, type SessionRecord, type TranscriptEntryRecord } from "@fitz/protocol";

interface ProjectRow { id: string; owner_user_id: string | null; name: string; root_path: string | null; created_at: string; updated_at: string }
interface SessionRow { id: string; project_id: string | null; workspace_root: string | null; owner_user_id: string | null; title: string; status: SessionRecord["status"]; connection_id: string; route_id: "default" | "fast" | "smart"; created_at: string; updated_at: string }
interface TranscriptRow { id: string; session_id: string; sequence: number; kind: TranscriptEntryRecord["kind"]; role: TranscriptEntryRecord["role"] | null; content_json: string; created_at: string }
interface ArtifactRow { id: string; session_id: string; name: string; mime_type: string; kind: ArtifactRecord["kind"]; byte_size: number; sha256: string; storage_backend: string; object_key: string; created_at: string; created_by_user_id: string | null; metadata_json: string }

export interface ArtifactStorageRef { backend: string; objectKey: string }
export interface LegacyArtifactContent { artifactId: string; content: Uint8Array }
export interface ArtifactStorageEntry { artifactId: string; backend: string; objectKey: string; byteSize: number; sha256: string }

/** Project, session, transcript, and artifact-catalog persistence. */
export class SqliteWorkspaceStore {
  constructor(private readonly database: DatabaseSync) {}

  createProject(project: ProjectRecord): void { this.database.prepare(`INSERT INTO projects (id, owner_user_id, name, root_path, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?)`).run(project.id, project.ownerUserId ?? null, project.name, project.rootPath ?? null, project.createdAt, project.updatedAt); }
  getProject(id: string): ProjectRecord | undefined { const row = this.database.prepare(`SELECT id, owner_user_id, name, root_path, created_at, updated_at FROM projects WHERE id = ?`).get(id) as ProjectRow | undefined; return row ? mapProject(row) : undefined; }
  listProjects(ownerUserId?: string): ProjectRecord[] { const rows = (ownerUserId ? this.database.prepare(`SELECT id, owner_user_id, name, root_path, created_at, updated_at FROM projects WHERE owner_user_id = ? ORDER BY updated_at DESC`).all(ownerUserId) : this.database.prepare(`SELECT id, owner_user_id, name, root_path, created_at, updated_at FROM projects ORDER BY updated_at DESC`).all()) as unknown as ProjectRow[]; return rows.map(mapProject); }
  updateProject(project: ProjectRecord): void { this.database.prepare(`UPDATE projects SET name = ?, root_path = ?, updated_at = ? WHERE id = ?`).run(project.name, project.rootPath ?? null, project.updatedAt, project.id); }
  deleteProject(id: string): boolean { this.database.exec("BEGIN IMMEDIATE"); try { this.database.prepare(`UPDATE agent_runs SET session_id = NULL WHERE session_id IN (SELECT id FROM sessions WHERE project_id = ?)`).run(id); const removed = this.database.prepare(`DELETE FROM projects WHERE id = ?`).run(id).changes > 0; this.database.exec("COMMIT"); return removed; } catch (error) { this.database.exec("ROLLBACK"); throw error; } }

  createSession(session: SessionRecord): void { this.database.prepare(`INSERT INTO sessions (id, project_id, workspace_root, owner_user_id, title, status, connection_id, route_id, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`).run(session.id, session.projectId ?? null, session.workspaceRoot ?? null, session.ownerUserId ?? null, session.title, session.status, session.connectionId ?? "hosted--local", session.routeId ?? "default", session.createdAt, session.updatedAt); }
  getSession(id: string): SessionRecord | undefined { const row = this.database.prepare(`SELECT id, project_id, workspace_root, owner_user_id, title, status, connection_id, route_id, created_at, updated_at FROM sessions WHERE id = ?`).get(id) as SessionRow | undefined; return row ? mapSession(row) : undefined; }
  listSessions(projectId: string, ownerUserId?: string): SessionRecord[] { const rows = (ownerUserId ? this.database.prepare(`SELECT id, project_id, workspace_root, owner_user_id, title, status, connection_id, route_id, created_at, updated_at FROM sessions WHERE project_id = ? AND owner_user_id = ? ORDER BY updated_at DESC`).all(projectId, ownerUserId) : this.database.prepare(`SELECT id, project_id, workspace_root, owner_user_id, title, status, connection_id, route_id, created_at, updated_at FROM sessions WHERE project_id = ? ORDER BY updated_at DESC`).all(projectId)) as unknown as SessionRow[]; return rows.map(mapSession); }
  listStandaloneSessions(ownerUserId?: string): SessionRecord[] { const rows = (ownerUserId ? this.database.prepare(`SELECT id, project_id, workspace_root, owner_user_id, title, status, connection_id, route_id, created_at, updated_at FROM sessions WHERE project_id IS NULL AND owner_user_id = ? ORDER BY updated_at DESC`).all(ownerUserId) : this.database.prepare(`SELECT id, project_id, workspace_root, owner_user_id, title, status, connection_id, route_id, created_at, updated_at FROM sessions WHERE project_id IS NULL ORDER BY updated_at DESC`).all()) as unknown as SessionRow[]; return rows.map(mapSession); }
  updateSession(session: SessionRecord): void { this.database.prepare(`UPDATE sessions SET title = ?, status = ?, workspace_root = ?, connection_id = ?, route_id = ?, updated_at = ? WHERE id = ?`).run(session.title, session.status, session.workspaceRoot ?? null, session.connectionId ?? "hosted--local", session.routeId ?? "default", session.updatedAt, session.id); }
  deleteSession(id: string): boolean { this.database.exec("BEGIN IMMEDIATE"); try { this.database.prepare(`UPDATE agent_runs SET session_id = NULL WHERE session_id = ?`).run(id); const removed = this.database.prepare(`DELETE FROM sessions WHERE id = ?`).run(id).changes > 0; this.database.exec("COMMIT"); return removed; } catch (error) { this.database.exec("ROLLBACK"); throw error; } }

  appendTranscriptEntry(entry: Omit<TranscriptEntryRecord, "sequence">): TranscriptEntryRecord {
    const ownsTransaction = !this.database.isTransaction;
    if (ownsTransaction) this.database.exec("BEGIN IMMEDIATE");
    try {
      const row = this.database.prepare(`SELECT COALESCE(MAX(sequence), 0) + 1 AS sequence FROM transcript_entries WHERE session_id = ?`).get(entry.sessionId) as { sequence: number };
      const content = entry.kind === "message" ? withChatContentDocument(entry.content) : entry.content;
      const complete: TranscriptEntryRecord = { ...entry, content, sequence: row.sequence };
      this.database.prepare(`INSERT INTO transcript_entries (id, session_id, sequence, kind, role, content_json, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)`).run(complete.id, complete.sessionId, complete.sequence, complete.kind, complete.role ?? null, JSON.stringify(complete.content), complete.createdAt);
      this.database.prepare(`UPDATE sessions SET updated_at = ?, transcript_revision = transcript_revision + 1 WHERE id = ?`).run(complete.createdAt, complete.sessionId);
      if (ownsTransaction) this.database.exec("COMMIT");
      return complete;
    } catch (error) {
      if (ownsTransaction) this.database.exec("ROLLBACK");
      throw error;
    }
  }
  getTranscriptEntry(id: string): TranscriptEntryRecord | undefined { const row = this.database.prepare(`SELECT id, session_id, sequence, kind, role, content_json, created_at FROM transcript_entries WHERE id = ?`).get(id) as TranscriptRow | undefined; return row ? mapTranscript(row) : undefined; }
  transcriptAfter(sessionId: string, sequence: number, limit = 1000): TranscriptEntryRecord[] { return (this.database.prepare(`SELECT id, session_id, sequence, kind, role, content_json, created_at FROM transcript_entries WHERE session_id = ? AND sequence > ? ORDER BY sequence LIMIT ?`).all(sessionId, sequence, limit) as unknown as TranscriptRow[]).map(mapTranscript); }
  transcriptBefore(sessionId: string, sequence: number, limit = 250): TranscriptEntryRecord[] { const rows = this.database.prepare(`SELECT id, session_id, sequence, kind, role, content_json, created_at FROM transcript_entries WHERE session_id = ? AND sequence < ? ORDER BY sequence DESC LIMIT ?`).all(sessionId, sequence, limit) as unknown as TranscriptRow[]; return rows.reverse().map(mapTranscript); }
  deleteTranscriptFrom(sessionId: string, sequence: number): number { const ownsTransaction = !this.database.isTransaction; if (ownsTransaction) this.database.exec("BEGIN IMMEDIATE"); try { const removed = Number(this.database.prepare(`DELETE FROM transcript_entries WHERE session_id = ? AND sequence >= ?`).run(sessionId, sequence).changes); if (removed > 0) this.database.prepare(`UPDATE sessions SET transcript_revision = transcript_revision + 1 WHERE id = ?`).run(sessionId); if (ownsTransaction) this.database.exec("COMMIT"); return removed; } catch (error) { if (ownsTransaction) this.database.exec("ROLLBACK"); throw error; } }
  hasTranscriptBefore(sessionId: string, sequence: number): boolean { return this.database.prepare(`SELECT 1 AS present FROM transcript_entries WHERE session_id = ? AND sequence < ? LIMIT 1`).get(sessionId, sequence) !== undefined; }
  latestTranscriptCompaction(sessionId: string): TranscriptEntryRecord | undefined { const row = this.database.prepare(`SELECT id, session_id, sequence, kind, role, content_json, created_at FROM transcript_entries WHERE session_id = ? AND kind = 'compaction' ORDER BY sequence DESC LIMIT 1`).get(sessionId) as TranscriptRow | undefined; return row ? mapTranscript(row) : undefined; }

  createArtifact(artifact: ArtifactRecord, storage: ArtifactStorageRef): void { this.database.prepare(`INSERT INTO artifacts (id, session_id, name, mime_type, kind, byte_size, sha256, storage_backend, object_key, created_at, created_by_user_id, metadata_json) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`).run(artifact.id, artifact.sessionId, artifact.name, artifact.mimeType, artifact.kind, artifact.byteSize, artifact.sha256, storage.backend, storage.objectKey, artifact.createdAt, artifact.createdByUserId ?? null, JSON.stringify(artifact.metadata)); }
  getArtifact(id: string): ArtifactRecord | undefined { const row = this.database.prepare(`SELECT id, session_id, name, mime_type, kind, byte_size, sha256, storage_backend, object_key, created_at, created_by_user_id, metadata_json FROM artifacts WHERE id = ?`).get(id) as ArtifactRow | undefined; return row ? mapArtifact(row) : undefined; }
  listArtifacts(sessionId: string): ArtifactRecord[] { return (this.database.prepare(`SELECT id, session_id, name, mime_type, kind, byte_size, sha256, storage_backend, object_key, created_at, created_by_user_id, metadata_json FROM artifacts WHERE session_id = ? ORDER BY created_at DESC`).all(sessionId) as unknown as ArtifactRow[]).map(mapArtifact); }
  getArtifactStorage(id: string): ArtifactStorageRef | undefined { const row = this.database.prepare(`SELECT storage_backend, object_key FROM artifacts WHERE id = ?`).get(id) as Pick<ArtifactRow, "storage_backend" | "object_key"> | undefined; return row ? { backend: row.storage_backend, objectKey: row.object_key } : undefined; }
  listArtifactStorage(backend: string): ArtifactStorageRef[] { return (this.database.prepare(`SELECT storage_backend, object_key FROM artifacts WHERE storage_backend = ?`).all(backend) as unknown as Array<Pick<ArtifactRow, "storage_backend" | "object_key">>).map((row) => ({ backend: row.storage_backend, objectKey: row.object_key })); }
  listArtifactStorageEntries(): ArtifactStorageEntry[] { return (this.database.prepare(`SELECT id, storage_backend, object_key, byte_size, sha256 FROM artifacts ORDER BY id`).all() as unknown as Array<{ id: string; storage_backend: string; object_key: string; byte_size: number; sha256: string }>).map((row) => ({ artifactId: row.id, backend: row.storage_backend, objectKey: row.object_key, byteSize: row.byte_size, sha256: row.sha256 })); }
  deleteArtifact(id: string): boolean { return this.database.prepare(`DELETE FROM artifacts WHERE id = ?`).run(id).changes > 0; }
  nextLegacyArtifactContent(): LegacyArtifactContent | undefined { if (!this.legacyArtifactsExist()) return undefined; const row = this.database.prepare(`SELECT id, content FROM artifacts_legacy ORDER BY id LIMIT 1`).get() as { id: string; content: Uint8Array } | undefined; return row ? { artifactId: row.id, content: row.content } : undefined; }
  countLegacyArtifactRefs(): number { return Number((this.database.prepare(`SELECT COUNT(*) AS count FROM artifacts WHERE storage_backend = 'legacy-sqlite'`).get() as { count: number }).count); }
  migrateArtifactStorage(id: string, artifact: Pick<ArtifactRecord, "byteSize" | "sha256">, storage: ArtifactStorageRef): void { this.database.prepare(`UPDATE artifacts SET byte_size = ?, sha256 = ?, storage_backend = ?, object_key = ? WHERE id = ?`).run(artifact.byteSize, artifact.sha256, storage.backend, storage.objectKey, id); if (this.legacyArtifactsExist()) this.database.prepare(`DELETE FROM artifacts_legacy WHERE id = ?`).run(id); }
  dropLegacyArtifacts(): void { if (this.legacyArtifactsExist()) this.database.exec(`DROP TABLE artifacts_legacy`); }
  compactArtifactMigration(): void { this.database.exec(`PRAGMA wal_checkpoint(TRUNCATE); VACUUM;`); }
  private legacyArtifactsExist(): boolean { return Boolean(this.database.prepare(`SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'artifacts_legacy'`).get()); }
}

function mapProject(row: ProjectRow): ProjectRecord { return { id: row.id, name: row.name, createdAt: row.created_at, updatedAt: row.updated_at, ...(row.owner_user_id ? { ownerUserId: row.owner_user_id } : {}), ...(row.root_path ? { rootPath: row.root_path } : {}) }; }
function mapSession(row: SessionRow): SessionRecord { return { id: row.id, title: row.title, status: row.status, connectionId: row.connection_id, routeId: row.route_id, createdAt: row.created_at, updatedAt: row.updated_at, ...(row.project_id ? { projectId: row.project_id } : {}), ...(row.workspace_root ? { workspaceRoot: row.workspace_root } : {}), ...(row.owner_user_id ? { ownerUserId: row.owner_user_id } : {}) }; }
function mapTranscript(row: TranscriptRow): TranscriptEntryRecord { return { id: row.id, sessionId: row.session_id, sequence: row.sequence, kind: row.kind, content: JSON.parse(row.content_json) as Record<string, unknown>, createdAt: row.created_at, ...(row.role ? { role: row.role } : {}) }; }
function mapArtifact(row: ArtifactRow): ArtifactRecord { return { id: row.id, sessionId: row.session_id, name: row.name, mimeType: row.mime_type, kind: row.kind, byteSize: row.byte_size, sha256: row.sha256, createdAt: row.created_at, metadata: JSON.parse(row.metadata_json) as Record<string, unknown>, ...(row.created_by_user_id ? { createdByUserId: row.created_by_user_id } : {}) }; }
