import type { AgentRuntimeEvent } from "@fitz/agent-core";

export type PiTurnOutputPhase = "working" | "finalized" | "media-handoff" | "failed";
export type PiInternalPromptPurpose = "delegation" | "plan" | "worker-report";

export interface PiTurnOutputPlan {
  required?(): boolean;
  phase(): "missing" | "active" | "ready_for_answer" | "completed";
}

export interface PiTurnOutputStateOptions {
  plan?: PiTurnOutputPlan;
  delegated: boolean;
  emit: (event: AgentRuntimeEvent) => void;
  discardAssistantDraft: () => void;
  /** Removes held answer text while preserving the tool call that follows it. */
  withholdAssistantDraftForTool: (toolCallId: string) => void;
}

/**
 * Mechanical state machine for one Pi turn's visible output.
 *
 * Pi can produce assistant drafts before a durable plan is answerable, after a
 * plan-ready tool call, or while a delegated worker is still using tools. This
 * class owns which output is buffered, emitted, discarded from model history,
 * or accepted as the final answer. Transport, tool policy, and prompting stay
 * in PiAgentRuntime.
 */
export class PiTurnOutputState {
  readonly #options: PiTurnOutputStateOptions;
  #phase: PiTurnOutputPhase = "working";
  #sawAssistant = false;
  #sawFinalAssistant = false;
  #bufferedAssistant: AgentRuntimeEvent[] = [];
  readonly #readyCandidates = new Map<string, AgentRuntimeEvent[]>();
  #pendingInternalPrompt: PiInternalPromptPurpose | undefined;
  #workerReportCandidate = false;

  constructor(options: PiTurnOutputStateOptions) {
    this.#options = options;
  }

  get phase(): PiTurnOutputPhase { return this.#phase; }
  get sawAssistant(): boolean { return this.#sawAssistant; }
  get sawFinalAssistant(): boolean { return this.#sawFinalAssistant; }
  get hasWorkerReportCandidate(): boolean { return this.#workerReportCandidate; }
  get shouldIgnorePromptError(): boolean { return this.#phase === "finalized"; }

  /** Emits ordinary output immediately and buffers plan-gated assistant text. */
  accept(event: AgentRuntimeEvent): void {
    if (this.#phase !== "working") return;
    if (this.#options.plan && event.type === "assistant.delta") {
      this.#bufferedAssistant.push(event);
      return;
    }
    if (event.type === "assistant.delta") {
      this.#sawAssistant = true;
      if (this.#options.delegated) this.#workerReportCandidate = true;
    }
    this.#options.emit(event);
  }

  /**
   * Flushes commentary before ordinary tools, or holds a draft across the
   * plan-ready tool whose successful completion makes it the final answer.
   */
  beforeToolStart(toolCallId: string, capturesReadyAnswer: boolean): void {
    if (this.#options.plan && this.#bufferedAssistant.length) {
      const candidate = this.#bufferedAssistant;
      this.#bufferedAssistant = [];
      if (capturesReadyAnswer) {
        this.#readyCandidates.set(toolCallId, candidate);
        // Pi has already committed the assistant message containing this text
        // and the ready tool call. Strip only its text from active history now,
        // before any tool result becomes the leaf. The candidate remains here
        // until the host-owned plan accepts or rejects the transition.
        this.#options.withholdAssistantDraftForTool(toolCallId);
      }
      else {
        const phase = this.#options.plan.phase();
        if (phase !== "ready_for_answer" && phase !== "completed") this.#emitAssistant(candidate, false);
      }
    }
    if (this.#options.delegated) this.#workerReportCandidate = false;
  }

  /** Returns true when Pi should be aborted because a held answer finalized. */
  afterToolEnd(toolCallId: string): boolean {
    const candidate = this.#readyCandidates.get(toolCallId);
    if (!candidate) return false;
    this.#readyCandidates.delete(toolCallId);
    if (this.#options.plan?.phase() !== "ready_for_answer") return false;
    this.#emitAssistant(candidate, true);
    this.#finalizePlanAnswer();
    return this.#phase === "finalized";
  }

  /** Reconciles one completed model prompt with the host-owned plan phase. */
  settleAfterPrompt(): void {
    const plan = this.#options.plan;
    if (!plan || this.#phase !== "working") return;
    const phase = plan.phase();
    if ((plan.required?.() ?? true) === false && phase === "missing") {
      this.#emitBufferedFinal();
      return;
    }
    if (phase === "ready_for_answer") {
      this.#emitBufferedFinal();
      return;
    }
    this.#discardBufferedAssistant();
  }

  expectInternalPrompt(purpose: PiInternalPromptPurpose): void {
    this.#pendingInternalPrompt = purpose;
  }

  /** Prevents a missing Pi echo from swallowing a later real steering message. */
  completeInternalPrompt(purpose: PiInternalPromptPurpose): void {
    if (this.#pendingInternalPrompt === purpose) this.#pendingInternalPrompt = undefined;
  }

  /** Consumes the Pi user-message echo generated by an internal continuation. */
  consumeInternalUserEcho(): boolean {
    if (!this.#pendingInternalPrompt) return false;
    this.#pendingInternalPrompt = undefined;
    return true;
  }

  beginMediaHandoff(): void {
    if (this.#phase === "working") this.#phase = "media-handoff";
  }

  /** Returns false when another terminal path already owns the turn. */
  beginFailure(): boolean {
    if (this.#phase !== "working") return false;
    this.#phase = "failed";
    return true;
  }

  /** Validates and finalizes a normally completed Pi session. */
  finish(): Error | undefined {
    if (this.#phase === "finalized") return undefined;
    if (this.#phase !== "working") return new Error(`Cannot finish a Pi turn from ${this.#phase}`);
    if (this.#options.plan) {
      if (!this.#sawFinalAssistant) return new Error("Pi agent completed without a final assistant response");
    } else if (!this.#sawAssistant) {
      return new Error("Pi agent completed without an assistant response");
    }
    this.#phase = "finalized";
    return undefined;
  }

  #emitBufferedFinal(): void {
    const events = this.#bufferedAssistant;
    this.#bufferedAssistant = [];
    this.#emitAssistant(events, true);
    this.#finalizePlanAnswer();
  }

  #emitAssistant(events: readonly AgentRuntimeEvent[], final: boolean): void {
    for (const event of events) this.#options.emit(event);
    if (!events.length) return;
    this.#sawAssistant = true;
    if (final) this.#sawFinalAssistant = true;
  }

  #finalizePlanAnswer(): void {
    if (this.#options.plan && this.#phase === "working" && this.#sawFinalAssistant) this.#phase = "finalized";
  }

  #discardBufferedAssistant(): void {
    if (!this.#bufferedAssistant.length) return;
    // UI suppression alone is insufficient: Pi keeps this draft in both model
    // histories, so it must be evicted before a continuation can be requested.
    this.#options.discardAssistantDraft();
    this.#bufferedAssistant = [];
  }
}
