packages:
  - apps/*
  - packages/*

injectWorkspacePackages: true

onlyBuiltDependencies:
  - esbuild
  - '@google/genai'
  - protobufjs
allowBuilds:
  '@google/genai': true
  electron-winstaller: true
  esbuild: true
  protobufjs: true
