import { contextBridge, ipcRenderer } from "electron";
export interface DesktopUpdateStatus { state: "idle" | "checking" | "available" | "downloading" | "current" | "downloaded" | "error" | "development"; percent?: number; version?: string }
export type ConsumerTemplate = "openai-compatible" | "openai-media" | "fal" | "replicate";
export interface ConsumerMediaModelSummary { id: string; routeId: string; recipeId: string; modality: "image" | "video" | "audio"; template: ConsumerTemplate }
export type InferenceExecutionClass = "self_hosted" | "metered_cloud";
export type HostAccessClass = "same_device" | "trusted_remote" | "public_remote";
export interface ConsumerConnectionSummary { id: string; displayName: string; baseUrl: string; authType: "none" | "bearer"; hasCredential: boolean; template: ConsumerTemplate; executionClass: InferenceExecutionClass; accessClass: HostAccessClass; models: Array<{ id: string; recipeId: string }>; mediaModels: ConsumerMediaModelSummary[]; updatedAt: string }
export interface ConsumerConnectionInput { id?: string; displayName: string; baseUrl?: string; authType: "none" | "bearer"; apiKey?: string; template?: ConsumerTemplate; executionClass: InferenceExecutionClass; modelIds?: string[] }
export interface ResourcePreview { kind: "markdown" | "html" | "code" | "text" | "image" | "pdf" | "audio" | "video"; name: string; path: string; content: string; size: number; line?: number; mimeType?: string; base64?: string }
export interface InAppBrowserState { url: string; title: string; canGoBack: boolean; canGoForward: boolean; loading: boolean; error?: string }
export type InAppBrowserAction = "back" | "forward" | "reload" | "stop" | "show" | "hide" | "close";
export type AgentEventStreamMessage =
  | { type: "event"; event: Record<string, unknown> }
  | { type: "end" }
  | { type: "error"; error: string };
export interface DesktopBridge { request(input: { path: string; method?: string; body?: unknown; responseType?: "text" | "base64" }): Promise<{ status: number; body: string }>; subscribeAgentEvents(input: { runId: string; after: number }, listener: (message: AgentEventStreamMessage) => void): () => void; bootstrapLocalDevice(): Promise<boolean>; configureHost(origin: string): Promise<void>; connectRemote(input: { origin: string; apiKey: string }): Promise<void>; listConsumerConnections(): Promise<ConsumerConnectionSummary[]>; saveConsumerConnection(input: ConsumerConnectionInput): Promise<ConsumerConnectionSummary>; removeConsumerConnection(id: string): Promise<void>; syncConsumerConnections(): Promise<Array<{ id: string; connected: boolean; error?: string }>>; connectionInfo(): Promise<{ origin: string; isLoopback: boolean; explicitlyConfigured: boolean; accessClass: HostAccessClass }>; chooseFolder(): Promise<string | undefined>; openPath(path: string): Promise<void>; previewResource(input: { projectRoot: string; reference: string; searchRoots?: string[] }): Promise<ResourcePreview>; copyText(value: string): Promise<void>; saveDiagnostics(content: string): Promise<string | undefined>; openExternal(url: string): Promise<void>; openBrowser(url: string): Promise<void>; setBrowserBounds(bounds: { x: number; y: number; width: number; height: number }): Promise<void>; browserAction(action: InAppBrowserAction): Promise<void>; onBrowserState(listener: (state: InAppBrowserState) => void): () => void; gitBranches(path: string): Promise<{ current: string; branches: string[] }>; checkoutBranch(path: string, branch: string): Promise<{ current: string; branches: string[] }>; createBranch(path: string, branch: string): Promise<{ current: string; branches: string[] }>; createWorktree(path: string, branch: string): Promise<{ path: string; branch: string }>; windowAction(action: "minimize" | "maximize" | "close"): Promise<void>; editCommand(command: "undo" | "redo" | "cut" | "copy" | "paste" | "select-all" | "reload" | "devtools"): Promise<void>; updateStatus(): Promise<DesktopUpdateStatus>; checkForUpdates(): Promise<void>; installUpdate(): Promise<void>; onUpdateStatus(listener: (status: DesktopUpdateStatus) => void): () => void; onNavigationCommand(listener: (command: "back" | "forward") => void): () => void }
const bridge: DesktopBridge = { request: (input) => ipcRenderer.invoke("fitz:request", input), subscribeAgentEvents, bootstrapLocalDevice: () => ipcRenderer.invoke("fitz:bootstrap-local-device"), configureHost: (origin) => ipcRenderer.invoke("fitz:configure-host", origin), connectRemote: (input) => ipcRenderer.invoke("fitz:connect-remote", input), listConsumerConnections: () => ipcRenderer.invoke("fitz:consumer-connections-list"), saveConsumerConnection: (input) => ipcRenderer.invoke("fitz:consumer-connection-save", input), removeConsumerConnection: (id) => ipcRenderer.invoke("fitz:consumer-connection-remove", id), syncConsumerConnections: () => ipcRenderer.invoke("fitz:consumer-connections-sync"), connectionInfo: () => ipcRenderer.invoke("fitz:connection-info"), chooseFolder: () => ipcRenderer.invoke("fitz:choose-folder"), openPath: (path) => ipcRenderer.invoke("fitz:open-path", path), previewResource: (input) => ipcRenderer.invoke("fitz:preview-resource", input), copyText: (value) => ipcRenderer.invoke("fitz:copy-text", value), saveDiagnostics: (content) => ipcRenderer.invoke("fitz:save-diagnostics", content), openExternal: (url) => ipcRenderer.invoke("fitz:open-external", url), openBrowser: (url) => ipcRenderer.invoke("fitz:browser-open", url), setBrowserBounds: (bounds) => ipcRenderer.invoke("fitz:browser-bounds", bounds), browserAction: (action) => ipcRenderer.invoke("fitz:browser-action", action), onBrowserState: (listener) => { const handler = (_event: unknown, state: unknown) => { if (isInAppBrowserState(state)) listener(state); }; ipcRenderer.on("fitz:browser-state", handler); return () => ipcRenderer.removeListener("fitz:browser-state", handler); }, gitBranches: (path) => ipcRenderer.invoke("fitz:git-branches", path), checkoutBranch: (path, branch) => ipcRenderer.invoke("fitz:git-checkout-branch", path, branch), createBranch: (path, branch) => ipcRenderer.invoke("fitz:git-create-branch", path, branch), createWorktree: (path, branch) => ipcRenderer.invoke("fitz:git-create-worktree", path, branch), windowAction: (action) => ipcRenderer.invoke("fitz:window-action", action), editCommand: (command) => ipcRenderer.invoke("fitz:edit-command", command), updateStatus: () => ipcRenderer.invoke("fitz:update-status"), checkForUpdates: () => ipcRenderer.invoke("fitz:update-check"), installUpdate: () => ipcRenderer.invoke("fitz:update-install"), onUpdateStatus: (listener) => { const handler = (_event: unknown, status: unknown) => { if (isDesktopUpdateStatus(status)) listener(status); }; ipcRenderer.on("fitz:update-status", handler); return () => ipcRenderer.removeListener("fitz:update-status", handler); }, onNavigationCommand: (listener) => { const handler = (_event: unknown, command: unknown) => { if (command === "back" || command === "forward") listener(command); }; ipcRenderer.on("fitz:navigation-command", handler); return () => ipcRenderer.removeListener("fitz:navigation-command", handler); } };
contextBridge.exposeInMainWorld("fitz", Object.freeze(bridge));
let agentEventSubscriptionSequence = 0;
function subscribeAgentEvents(input: { runId: string; after: number }, listener: (message: AgentEventStreamMessage) => void): () => void {
  const subscriptionId = `${Date.now().toString(36)}-${++agentEventSubscriptionSequence}`;
  const handler = (_event: unknown, value: unknown) => {
    if (!isRecord(value) || value.subscriptionId !== subscriptionId) return;
    if (value.type === "event" && isRecord(value.event)) listener({ type: "event", event: value.event });
    else if (value.type === "end") listener({ type: "end" });
    else if (value.type === "error" && typeof value.error === "string") listener({ type: "error", error: value.error });
  };
  ipcRenderer.on("fitz:agent-events", handler);
  ipcRenderer.send("fitz:agent-events-subscribe", { subscriptionId, runId: input.runId, after: input.after });
  let active = true;
  return () => {
    if (!active) return;
    active = false;
    ipcRenderer.removeListener("fitz:agent-events", handler);
    ipcRenderer.send("fitz:agent-events-unsubscribe", subscriptionId);
  };
}
function isDesktopUpdateStatus(value: unknown): value is DesktopUpdateStatus { return typeof value === "object" && value !== null && "state" in value && typeof value.state === "string"; }
function isInAppBrowserState(value: unknown): value is InAppBrowserState { return typeof value === "object" && value !== null && "url" in value && typeof value.url === "string" && "title" in value && typeof value.title === "string" && "canGoBack" in value && typeof value.canGoBack === "boolean" && "canGoForward" in value && typeof value.canGoForward === "boolean" && "loading" in value && typeof value.loading === "boolean"; }
function isRecord(value: unknown): value is Record<string, unknown> { return typeof value === "object" && value !== null && !Array.isArray(value); }
