type Json = Record<string, any>; let currentProject: string | undefined; let currentSession: string | undefined; let lastSequence = 0;
const projects = element("projects"); const sessions = element("sessions"); const messages = element("messages"); const model = element("model") as HTMLSelectElement; const form = element("composer") as HTMLFormElement; const prompt = element("prompt") as HTMLTextAreaElement; const status = element("status");

void initialize();
form.addEventListener("submit", (event) => { event.preventDefault(); void sendPrompt(); });
element("new-project").addEventListener("click", () => void createProject()); element("new-session").addEventListener("click", () => void createSession());

async function initialize(): Promise<void> { try { setStatus("Connecting…", "loading"); const [health, models] = await Promise.all([api("/health"), api("/v1/models")]); for (const card of models.data ?? []) model.add(new Option(card.display_name ?? card.id, card.id)); setStatus(health.engine?.state ?? "UNLOADED", "idle"); await loadProjects(); } catch (error) { setStatus(errorMessage(error), "error"); } }
async function loadProjects(): Promise<void> { const response = await api("/api/v1/projects"); projects.replaceChildren(); for (const project of response.data ?? []) projects.append(button(project.name, () => selectProject(project.id))); if (!currentProject && response.data?.[0]) await selectProject(response.data[0].id); }
async function selectProject(id: string): Promise<void> { currentProject = id; currentSession = undefined; lastSequence = 0; messages.replaceChildren(empty("Select or create a task")); const response = await api(`/api/v1/projects/${id}/sessions`); sessions.replaceChildren(); for (const session of response.data ?? []) sessions.append(button(session.title, () => selectSession(session.id))); if (response.data?.[0]) await selectSession(response.data[0].id); }
async function selectSession(id: string): Promise<void> { currentSession = id; lastSequence = 0; messages.replaceChildren(); const transcript = await api(`/api/v1/sessions/${id}/transcript`); for (const entry of transcript.data ?? []) if (entry.kind === "message") appendMessage(entry.role ?? "system", entry.content?.text ?? ""); }
async function createProject(): Promise<void> { const name = window.prompt("Project name"); if (!name) return; const response = await api("/api/v1/projects", "POST", { name }); currentProject = response.data.id; await loadProjects(); await selectProject(response.data.id); }
async function createSession(): Promise<void> { if (!currentProject) return; const title = window.prompt("Task name"); if (!title) return; const response = await api(`/api/v1/projects/${currentProject}/sessions`, "POST", { title }); await selectProject(currentProject); await selectSession(response.data.id); }
async function sendPrompt(): Promise<void> { const content = prompt.value.trim(); if (!content || !currentSession || !model.value) return; prompt.value = ""; appendMessage("user", content); setStatus("Queued", "loading"); try { const response = await api("/api/v1/agent/runs", "POST", { model: model.value, sessionId: currentSession, messages: [{ role: "user", content }] }); await followRun(response.data.id); } catch (error) { appendMessage("system", errorMessage(error)); setStatus("Failed", "error"); } }
async function followRun(runId: string): Promise<void> { let assistant: HTMLElement | undefined; let done = false; while (!done) { const replay = await api(`/api/v1/agent/runs/${runId}/events?after=${lastSequence}`); for (const event of replay.events ?? []) { lastSequence = event.sequence; if (event.type === "run.started") setStatus("Running", "active"); if (event.type === "assistant.delta") { assistant ??= appendMessage("assistant", ""); assistant.textContent += event.data.text ?? ""; } if (["run.completed", "run.failed", "run.cancelled", "run.interrupted"].includes(event.type)) { done = true; setStatus(event.type.slice(4), event.type === "run.completed" ? "idle" : "error"); } } if (!done) await new Promise((resolve) => setTimeout(resolve, 400)); } }
async function api(path: string, method = "GET", body?: unknown): Promise<Json> { const response = await window.fitz.request({ path, method, ...(body !== undefined ? { body } : {}) }); let parsed: Json; try { parsed = JSON.parse(response.body) as Json; } catch { parsed = { error: response.body }; } if (response.status >= 400) throw new Error(parsed.error?.message ?? parsed.error ?? `Request failed (${response.status})`); return parsed; }
function appendMessage(role: string, text: string): HTMLElement { if (messages.firstElementChild?.classList.contains("empty")) messages.replaceChildren(); const article = document.createElement("article"); article.className = `message ${role}`; const label = document.createElement("small"); label.textContent = role; const content = document.createElement("div"); content.textContent = text; article.append(label, content); messages.append(article); article.scrollIntoView({ block: "end" }); return content; }
function button(label: string, action: () => void): HTMLButtonElement { const value = document.createElement("button"); value.type = "button"; value.textContent = label; value.addEventListener("click", action); return value; }
function empty(text: string): HTMLElement { const value = document.createElement("p"); value.className = "empty"; value.textContent = text; return value; }
function element(id: string): HTMLElement { const value = document.getElementById(id); if (!value) throw new Error(`Missing #${id}`); return value; }
function setStatus(text: string, state: string): void { status.textContent = text; status.dataset.state = state; }
function errorMessage(error: unknown): string { return error instanceof Error ? error.message : String(error); }
