import { reconnectDelay } from "@fitz/connectivity/reconnect";
type Json = Record<string, any>; let currentProject: string | undefined; let currentSession: string | undefined; let lastSequence = 0;
const projects = element("projects"); const sessions = element("sessions"); const messages = element("messages"); const model = element("model") as HTMLSelectElement; const form = element("composer") as HTMLFormElement; const prompt = element("prompt") as HTMLTextAreaElement; const status = element("status");
const artifacts = element("artifacts"); const artifactPreview = element("artifact-preview"); const artifactFile = element("artifact-file") as HTMLInputElement;

void initialize();
form.addEventListener("submit", (event) => { event.preventDefault(); void sendPrompt(); });
element("new-project").addEventListener("click", () => void createProject()); element("new-session").addEventListener("click", () => void createSession());
element("add-artifact").addEventListener("click", () => artifactFile.click()); artifactFile.addEventListener("change", () => void uploadArtifact());

async function initialize(): Promise<void> { try { setStatus("Connecting…", "loading"); const [health, models] = await Promise.all([api("/health"), api("/v1/models")]); for (const card of models.data ?? []) model.add(new Option(card.display_name ?? card.id, card.id)); setStatus(health.engine?.state ?? "UNLOADED", "idle"); await loadProjects(); } catch (error) { setStatus(errorMessage(error), "error"); } }
async function loadProjects(): Promise<void> { const response = await api("/api/v1/projects"); projects.replaceChildren(); for (const project of response.data ?? []) projects.append(button(project.name, () => selectProject(project.id))); if (!currentProject && response.data?.[0]) await selectProject(response.data[0].id); }
async function selectProject(id: string): Promise<void> { currentProject = id; currentSession = undefined; lastSequence = 0; messages.replaceChildren(empty("Select or create a task")); const response = await api(`/api/v1/projects/${id}/sessions`); sessions.replaceChildren(); for (const session of response.data ?? []) sessions.append(button(session.title, () => selectSession(session.id))); if (response.data?.[0]) await selectSession(response.data[0].id); }
async function selectSession(id: string): Promise<void> { currentSession = id; lastSequence = 0; messages.replaceChildren(); const [transcript] = await Promise.all([api(`/api/v1/sessions/${id}/transcript`), loadArtifacts()]); for (const entry of transcript.data ?? []) if (entry.kind === "message") appendMessage(entry.role ?? "system", entry.content?.text ?? ""); }
async function createProject(): Promise<void> { const name = window.prompt("Project name"); if (!name) return; const response = await api("/api/v1/projects", "POST", { name }); currentProject = response.data.id; await loadProjects(); await selectProject(response.data.id); }
async function createSession(): Promise<void> { if (!currentProject) return; const title = window.prompt("Task name"); if (!title) return; const response = await api(`/api/v1/projects/${currentProject}/sessions`, "POST", { title }); await selectProject(currentProject); await selectSession(response.data.id); }
async function loadArtifacts(): Promise<void> { artifacts.replaceChildren(); artifactPreview.replaceChildren(empty("No artifact selected")); if (!currentSession) return; const response = await api(`/api/v1/sessions/${currentSession}/artifacts`); for (const artifact of response.data ?? []) artifacts.append(button(`${artifact.name} · ${formatBytes(artifact.byteSize)}`, () => void previewArtifact(artifact))); }
async function uploadArtifact(): Promise<void> { const file = artifactFile.files?.[0]; artifactFile.value = ""; if (!file || !currentSession) return; if (file.size > 1_500_000) { window.alert("Artifacts are currently limited to 1.5 MB."); return; } const contentBase64 = bytesToBase64(new Uint8Array(await file.arrayBuffer())); await api(`/api/v1/sessions/${currentSession}/artifacts`, "POST", { name: file.name, mimeType: file.type || "application/octet-stream", contentBase64 }); await loadArtifacts(); }
async function previewArtifact(artifact: Json): Promise<void> { const response = await window.fitz.request({ path: `/api/v1/artifacts/${artifact.id}/content`, responseType: "base64" }); if (response.status >= 400) throw new HttpError("Artifact could not be loaded", response.status); artifactPreview.replaceChildren(); if (artifact.kind === "text" || artifact.kind === "code") { const pre = document.createElement("pre"); pre.textContent = new TextDecoder().decode(base64Bytes(response.body)); artifactPreview.append(pre); return; } if (["image", "audio", "video"].includes(artifact.kind)) { const node = document.createElement(artifact.kind === "image" ? "img" : artifact.kind) as HTMLImageElement | HTMLMediaElement; node.setAttribute("src", `data:${artifact.mimeType};base64,${response.body}`); if (node instanceof HTMLMediaElement) node.controls = true; artifactPreview.append(node); return; } if (artifact.kind === "pdf") { const frame = document.createElement("iframe"); frame.setAttribute("sandbox", ""); frame.title = artifact.name; frame.src = `data:application/pdf;base64,${response.body}`; artifactPreview.append(frame); return; } artifactPreview.append(empty("Preview unavailable for this file type")); }
async function sendPrompt(): Promise<void> { const content = prompt.value.trim(); if (!content || !currentSession || !model.value) return; prompt.value = ""; appendMessage("user", content); setStatus("Queued", "loading"); try { const response = await api("/api/v1/agent/runs", "POST", { model: model.value, sessionId: currentSession, messages: [{ role: "user", content }] }); await followRun(response.data.id); } catch (error) { appendMessage("system", errorMessage(error)); setStatus("Failed", "error"); } }
async function followRun(runId: string): Promise<void> { let assistant: HTMLElement | undefined; let done = false; let reconnectAttempt = 0; while (!done) { let replay: Json; try { replay = await api(`/api/v1/agent/runs/${runId}/events?after=${lastSequence}`); reconnectAttempt = 0; } catch (error) { if (error instanceof HttpError || reconnectAttempt >= 12) throw error; setStatus(`Reconnecting (${reconnectAttempt + 1})…`, "loading"); await new Promise((resolve) => setTimeout(resolve, reconnectDelay(reconnectAttempt++))); continue; } for (const event of replay.events ?? []) { lastSequence = event.sequence; if (event.type === "run.started") setStatus("Running", "active"); if (event.type === "assistant.delta") { assistant ??= appendMessage("assistant", ""); assistant.textContent += event.data.text ?? ""; } if (["run.completed", "run.failed", "run.cancelled", "run.interrupted"].includes(event.type)) { done = true; setStatus(event.type.slice(4), event.type === "run.completed" ? "idle" : "error"); } } if (!done) await new Promise((resolve) => setTimeout(resolve, 400)); } }
async function api(path: string, method = "GET", body?: unknown): Promise<Json> { const response = await window.fitz.request({ path, method, ...(body !== undefined ? { body } : {}) }); let parsed: Json; try { parsed = JSON.parse(response.body) as Json; } catch { parsed = { error: response.body }; } if (response.status >= 400) throw new HttpError(parsed.error?.message ?? parsed.error ?? `Request failed (${response.status})`, response.status); return parsed; }
function appendMessage(role: string, text: string): HTMLElement { if (messages.firstElementChild?.classList.contains("empty")) messages.replaceChildren(); const article = document.createElement("article"); article.className = `message ${role}`; const label = document.createElement("small"); label.textContent = role; const content = document.createElement("div"); content.textContent = text; article.append(label, content); messages.append(article); article.scrollIntoView({ block: "end" }); return content; }
function button(label: string, action: () => void): HTMLButtonElement { const value = document.createElement("button"); value.type = "button"; value.textContent = label; value.addEventListener("click", action); return value; }
function empty(text: string): HTMLElement { const value = document.createElement("p"); value.className = "empty"; value.textContent = text; return value; }
function element(id: string): HTMLElement { const value = document.getElementById(id); if (!value) throw new Error(`Missing #${id}`); return value; }
function setStatus(text: string, state: string): void { status.textContent = text; status.dataset.state = state; }
function errorMessage(error: unknown): string { return error instanceof Error ? error.message : String(error); }
class HttpError extends Error { constructor(message: string, readonly status: number) { super(message); } }
function bytesToBase64(bytes: Uint8Array): string { let binary = ""; for (let index = 0; index < bytes.length; index += 0x8000) binary += String.fromCharCode(...bytes.subarray(index, index + 0x8000)); return btoa(binary); }
function base64Bytes(value: string): Uint8Array { const binary = atob(value); return Uint8Array.from(binary, (character) => character.charCodeAt(0)); }
function formatBytes(value: number): string { return value < 1024 ? `${value} B` : `${(value / 1024).toFixed(1)} KB`; }
