/**
 * run-verify.mjs — generate the `--patch` overlay for the installed DeepSeek
 * Harness and boot one verification session through it.
 *
 * Usage:
 *   node verify/run-verify.mjs --preset anchored-standard \
 *       --task "Understand this project." \
 *       --cwd "D:/scratch/verify-wd" \
 *       [--stop-after-first-assistant]
 *
 * The harness install is read from DSH_HARNESS_ROOT (default
 * D:/Software/deepseek-harness); the launcher binary is
 * apps/cli/lib/bin.js under that root. A generated overlay lives at
 * verify/patch.generated.yml and is recreated on every run.
 */

import { spawnSync } from 'node:child_process'
import { existsSync } from 'node:fs'
import { copyFileSync, writeFileSync, rmSync } from 'node:fs'
import { join } from 'node:path'
import { homedir } from 'node:os'
import { fileURLToPath } from 'node:url'
import { dirname } from 'node:path'

const HERE = dirname(fileURLToPath(import.meta.url))
const HARNESS = process.env.DSH_HARNESS_ROOT ?? 'D:/Software/deepseek-harness'
const LAUNCHER = join(HARNESS, 'apps', 'cli', 'lib', 'bin.js')
const DSH_HOME = process.env.DSH_HOME ?? join(homedir(), '.dsh')
const PROFILE_DIR = join(DSH_HOME, 'profiles', 'headless')

function usage() {
  console.error(
    'usage: node verify/run-verify.mjs --preset <id> --task <text> [--cwd <dir>] [--stop-after-first-assistant]',
  )
  process.exit(2)
}

const args = process.argv.slice(2)
const opts = { preset: 'anchored-standard', cwd: process.cwd(), stop: false }
for (let i = 0; i < args.length; i += 1) {
  switch (args[i]) {
    case '--preset': opts.preset = args[++i]; break
    case '--task': opts.task = args[++i]; break
    case '--cwd': opts.cwd = args[++i]; break
    case '--provider': opts.provider = args[++i]; break
    case '--model': opts.model = args[++i]; break
    case '--reasoning-effort': opts.reasoningEffort = args[++i]; break
    case '--stop-after-first-assistant': opts.stop = true; break
    case '--help': usage(); break
    default: usage()
  }
}
if (typeof opts.task !== 'string' || opts.task.trim() === '') usage()
if (!existsSync(LAUNCHER)) {
  console.error(`launcher not found: ${LAUNCHER} (set DSH_HARNESS_ROOT)`)
  process.exit(2)
}

// A YAML double-quoted scalar is a JSON string; JSON.stringify escapes exactly
// what YAML double-quoted strings accept (plus YAML's own escapes are a
// superset, so this round-trips every input).
const task = JSON.stringify(opts.task)
const cwd = JSON.stringify(opts.cwd)
// The runner module is copied beside the profile's cordis.yml: the loader
// resolves relative patch specifiers against the profile directory, and the
// profile's hoisted node_modules supplies the @deepseek-ai imports.
const runnerFile = join(PROFILE_DIR, 'verify-runner.mjs')
copyFileSync(`${HERE}/verify-runner.mjs`, runnerFile)
const rosterDefault = JSON.stringify('standard')

const patch = `# Generated by verify/run-verify.mjs — one-shot overlay for the headless
# profile that composes the agent-preset roster and the verify runner.
# The shipped headless runner is disabled: it owns the task positional and
# would error when this overlay's config does not supply one.
- id: headless-startup
  disabled: true

- id: headless-runner
  disabled: true

- insert:
    - id: agent-presets
      name: '@deepseek-ai/dsh-agent-presets'
      config:
        default: ${rosterDefault}

    - id: verify-runner
      name: ./verify-runner.mjs
      config:
        task: ${task}
        preset: ${JSON.stringify(opts.preset)}
        cwd: ${cwd}
        stopAfterFirstAssistant: ${opts.stop ? 'true' : 'false'}
        ${opts.provider === undefined ? '' : `provider: ${JSON.stringify(opts.provider)}`}
        ${opts.model === undefined ? '' : `model: ${JSON.stringify(opts.model)}`}
        ${opts.reasoningEffort === undefined ? '' : `reasoningEffort: ${JSON.stringify(opts.reasoningEffort)}`}
`

const patchFile = join(HERE, 'patch.generated.yml')
writeFileSync(patchFile, patch)

const result = spawnSync(
  process.execPath,
  [LAUNCHER, '--profile', 'headless', '--patch', patchFile],
  { cwd: HARNESS, stdio: 'inherit', encoding: 'utf8', env: process.env },
)
rmSync(patchFile, { force: true })
rmSync(runnerFile, { force: true })
process.exit(result.status ?? 1)
