#!/usr/bin/env node
/**
 * probe-clone — outer loop for the first-sentence anchoring probe.
 *
 * Installs the repo's prefab mode into a harness checkout as the preset
 * `prefab-anchored-standard` (with the chosen template.jsonl), then runs N
 * independent trials: each boots the headless profile, hydrates a fresh clone
 * session, sends one follow-up, and records the first reasoning line's family.
 * One model request per trial — the affordable trajectory measurement.
 *
 * Usage:
 *   DSH_HARNESS_ROOT=<checkout> node prefab/probe-clone.mjs \
 *       --cwd "E:/Desktop/mytests/prefab-generic-roll-workspace" \
 *       [--trials 4] [--template prefab/generic-candidate-v3.jsonl] \
 *       [--label v3] [--prompt "..."]
 *
 * Output: one line per trial + a closing tally (families and we/let-me).
 */

import { spawnSync } from 'node:child_process'
import { randomUUID } from 'node:crypto'
import { copyFileSync, existsSync, mkdirSync, rmSync, writeFileSync } from 'node:fs'
import { join, dirname, resolve } from 'node:path'
import { homedir } from 'node:os'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
const HARNESS = process.env.DSH_HARNESS_ROOT
const LAUNCHER = HARNESS && join(HARNESS, 'apps', 'cli', 'lib', 'bin.js')
const DSH_HOME = process.env.DSH_HOME ?? join(homedir(), '.dsh')
const PROFILE_DIR = join(DSH_HOME, 'profiles', 'headless')
const PRESET_DIR = HARNESS && join(HARNESS, 'apps', 'cli', 'config', 'agent-presets', 'prefab-anchored-standard')

const DEFAULT_FOLLOW_UP = 'Briefly summarize what has already been prepared in this session and what the next concrete step should be.'

const args = process.argv.slice(2)
const opt = (name, fallback) => {
  const hit = args.find((a) => a.startsWith(`--${name}=`))
  if (hit) return hit.slice(name.length + 3)
  const index = args.indexOf(`--${name}`)
  return index >= 0 && args[index + 1] !== undefined && !args[index + 1].startsWith('--')
    ? args[index + 1]
    : fallback
}
const cwd = opt('cwd')
const trials = Number(opt('trials', '4'))
const template = opt('template', join(HERE, 'template.jsonl'))
const label = opt('label', 'shipped')
const followUp = opt('prompt', DEFAULT_FOLLOW_UP)
if (cwd === undefined || !existsSync(LAUNCHER) || !existsSync(template)) {
  console.error('usage: DSH_HARNESS_ROOT=<checkout> node prefab/probe-clone.mjs --cwd <dir> [--trials N] [--template file] [--label name] [--prompt text]')
  process.exit(2)
}

/** The plugin files agent.cordis.yml references, plus the preset metadata. */
const PRESET_FILES = [
  'agent.cordis.yml', 'preset.yml', 'template.jsonl', 'template.jsonl.meta.json',
  'compaction-epoch.mjs', 'context-gate.mjs', 'custom-bash.mjs', 'dev-tool-search.mjs',
  'instruction-hint.mjs', 'prefab-session-seed.mjs', 'skill-search.mjs', 'tool-bootstrap.mjs',
]

mkdirSync(PRESET_DIR, { recursive: true })
for (const file of PRESET_FILES) {
  const source = join(HERE, file)
  if (existsSync(source)) copyFileSync(source, join(PRESET_DIR, file))
}
copyFileSync(resolve(template), join(PRESET_DIR, 'template.jsonl'))
console.log(`preset installed: ${PRESET_DIR} (template: ${label})`)

mkdirSync(PROFILE_DIR, { recursive: true })
const runToken = randomUUID()
const runnerName = `prefab-probe-runner-${runToken}.mjs`
const runnerFile = join(PROFILE_DIR, runnerName)
copyFileSync(join(HERE, 'probe-clone-runner.mjs'), runnerFile)

const results = []
try {
  for (let trial = 1; trial <= trials; trial += 1) {
    const patchFile = join(PROFILE_DIR, `prefab-probe-${runToken}.yml`)
    writeFileSync(patchFile, `# Generated by prefab/probe-clone.mjs (trial ${trial})
- id: headless-startup
  disabled: true

- id: headless-runner
  disabled: true

- insert:
    - id: agent-presets
      name: '@deepseek-ai/dsh-agent-presets'
      config:
        default: standard

    - id: probe-clone-runner
      name: ./${runnerName}
      config:
        followUp: ${JSON.stringify(followUp)}
        preset: prefab-anchored-standard
        cwd: ${JSON.stringify(cwd)}
`)
    const result = spawnSync(process.execPath, [LAUNCHER, '--profile', 'headless', '--patch', patchFile], {
      cwd: HARNESS, encoding: 'utf8', timeout: 300_000, env: process.env,
    })
    rmSync(patchFile, { force: true })
    const line = (result.stdout ?? '').split('\n').find((l) => l.startsWith('PROBE_RESULT: '))
    if ((result.stderr ?? '').trim().length > 0) {
      console.log(`  stderr: ${result.stderr.slice(-500).replace(/\n/g, '\n  ')}`)
    }
    if (line === undefined) {
      console.log(`trial ${trial}: NO VERDICT (exit ${result.status}); stderr: ${(result.stderr ?? '').slice(-300)}`)
      results.push({ ok: false, family: 'error' })
      continue
    }
    const verdict = JSON.parse(line.slice('PROBE_RESULT: '.length))
    console.log(`trial ${trial} [${label}]: family=${verdict.family} we=${verdict.we} letMe=${verdict.letMe} tools=${verdict.toolCallsInFirstMessage} seeded=${verdict.seeded} (${verdict.durationMs}ms)`)
    console.log(`  first: ${verdict.firstLine}`)
    results.push(verdict)
  }
} finally {
  rmSync(runnerFile, { force: true })
}

const tally = {}
for (const result of results) {
  const key = result.family ?? 'error'
  tally[key] = (tally[key] ?? 0) + 1
}
const anchored = (tally.we ?? 0) + (tally.lets ?? 0)
console.log(`SUMMARY [${label}]: ${JSON.stringify(tally)} — we/lets-first ${anchored}/${results.length}, let-me ${(tally['let-me'] ?? 0)}/${results.length}`)
